<script setup lang="ts">
import MarketIndices from '../components/MarketIndices.vue'
import { Globe, TrendingUp } from 'lucide-vue-next'
</script>

<template>
  <div class="p-6 lg:p-10 space-y-10 lg:space-y-12 max-w-[1600px] mx-auto w-full pb-16">
    <!-- Header Section -->
    <div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 overflow-hidden">
      <div class="space-y-2">
        <div class="flex items-center gap-4">
          <div class="p-2.5 bg-bloomberg-amber/10 border border-bloomberg-amber/20 rounded-xl">
             <Globe class="w-6 h-6 text-bloomberg-amber" />
          </div>
          <h1 class="text-3xl lg:text-4xl font-black font-outfit tracking-tighter uppercase text-white">Market Intelligence</h1>
        </div>
        <p class="text-neutral-500 text-[10px] font-bold uppercase tracking-[0.3em] ml-16">Global Indices & Equities • Real-time Data</p>
      </div>

      <div class="flex items-center gap-4 w-full md:w-auto">
        <div class="hidden sm:flex items-center gap-2 px-4 py-2 bg-white/[0.02] border border-white/5 rounded-full">
           <div class="w-1.5 h-1.5 rounded-full bg-zen-green animate-pulse"></div>
           <span class="text-[9px] font-black text-neutral-400 uppercase tracking-widest">Market Open</span>
        </div>
      </div>
    </div>

    <!-- Main Content -->
    <MarketIndices />
    
    <!-- Additional Info / Footer -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6 pt-10 border-t border-white/5">
        <div class="space-y-4">
             <h3 class="text-lg font-black font-outfit text-white uppercase tracking-tight">Market Brief</h3>
             <p class="text-xs text-neutral-500 leading-relaxed max-w-xl">
                 Data provided by Finnhub and Twelve Data. Quotes are delayed by at least 15 minutes unless otherwise noted. 
                 Market analysis is generated by automated algorithms and should not be considered as financial advice.
                 Past performance is not indicative of future results.
             </p>
        </div>
        <div class="flex justify-start md:justify-end items-start">
             <div class="p-4 rounded-xl bg-white/[0.03] border border-white/5 flex gap-4 items-center">
                 <TrendingUp class="w-8 h-8 text-neutral-700" />
                 <div>
                     <p class="text-[10px] font-black text-white uppercase tracking-widest">Sentiment Analysis</p>
                     <p class="text-[20px] font-black text-zen-green tracking-tighter tabular-nums">BULLISH</p>
                 </div>
             </div>
        </div>
    </div>
  </div>
</template>
